#!/bin/bash
# raw-to-patterns.sh — 把 token-log.jsonl 的 raw 数据升级成 "成本模式"(patterns/)
#
# 每次运行扫描 raw/token-log.jsonl,按 skill 聚合,产出:
#   patterns/pattern-token-{skill}-{date}.md
#
# 每份 pattern 含:
#   - P50/P90/P99 output token(判定 skill 稳定性)
#   - 样本数 / 时间范围
#   - 异常点标记(超过 P90 的 run,提示 review)
#   - 成本估算($)
#   - 建议 budget(供人工审核后升级到 rules/)
#
# 使用:
#   ./raw-to-patterns.sh             # 只处理 --clean 后数据,样本 >= 3 的 skill
#   ./raw-to-patterns.sh --min 5     # 自定义最小样本数
#   ./raw-to-patterns.sh --skill pm-retrospective   # 只处理特定 skill
#
# 设计定位:本脚本产出"待审核"的 pattern,不是最终 rule。
# 人工看完后,把可信的 pattern 升级到 rules/rule-token-{skill}.md,再反哺到 SKILL.md 的 budget 声明。

set -uo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
log="${WORKFLOW_DLC_LOG_DIR:-${script_dir}/raw}/token-log.jsonl"
patterns_dir="${script_dir}/patterns"
mkdir -p "$patterns_dir"

if [ ! -f "$log" ]; then
  echo "No raw token log yet: $log"
  exit 0
fi

# ── 参数解析 ──
min_samples=3
target_skill=""
while [ $# -gt 0 ]; do
  case "$1" in
    --min) min_samples="$2"; shift 2 ;;
    --skill) target_skill="$2"; shift 2 ;;
    *) echo "Usage: $0 [--min N] [--skill <name>]"; exit 1 ;;
  esac
done

# ── 拉 clean 数据(剔除每 session 首轮全量脏数据) ──
clean_data=$(jq -s '
  group_by(.session_id)
  | map(if length > 1 then .[1:] else [] end)
  | flatten
  | map(select(.skill != "untracked"))
' "$log")

# ── 按 skill 分组 ──
skills=$(echo "$clean_data" | jq -r '[.[].skill] | unique | .[]')

today=$(date +%Y-%m-%d)
processed=0

for skill in $skills; do
  # 跳过不匹配 target_skill 的
  [ -n "$target_skill" ] && [ "$target_skill" != "$skill" ] && continue

  # 过滤该 skill 的数据
  skill_data=$(echo "$clean_data" | jq --arg s "$skill" '[.[] | select(.skill == $s)]')
  sample_count=$(echo "$skill_data" | jq 'length')

  # 样本不够跳过
  if [ "$sample_count" -lt "$min_samples" ]; then
    continue
  fi

  # 算 P50/P90/P99 output tokens
  stats=$(echo "$skill_data" | jq '
    map(.turn_delta.output_tokens) as $outputs
    | ($outputs | sort) as $sorted
    | {
        samples: length,
        p50: $sorted[($sorted | length / 2 | floor)],
        p90: $sorted[($sorted | length * 0.9 | floor)],
        p99: $sorted[($sorted | length * 0.99 | floor)],
        max: ($sorted | max),
        min: ($sorted | min),
        avg: ($sorted | add / length | floor)
      }
  ')

  # 算总成本(USD)
  cost=$(echo "$skill_data" | jq '
    {
      output_usd: ((map(.turn_delta.output_tokens) | add) / 1000000 * 75),
      cache_read_usd: ((map(.turn_delta.cache_read) | add) / 1000000 * 1.5),
      cache_creation_usd: ((map(.turn_delta.cache_creation) | add) / 1000000 * 18.75),
      input_usd: ((map(.turn_delta.input_tokens) | add) / 1000000 * 15)
    }
    | . + {total_usd: (.output_usd + .cache_read_usd + .cache_creation_usd + .input_usd)}
  ')

  # 找异常点(output > P90 的 run)
  outliers=$(echo "$skill_data" | jq --argjson p90 "$(echo "$stats" | jq .p90)" '
    map(select(.turn_delta.output_tokens > $p90))
    | map({ts:.timestamp, session_id, output:.turn_delta.output_tokens})
  ')

  # 时间范围
  first_ts=$(echo "$skill_data" | jq -r '[.[].timestamp] | sort | first')
  last_ts=$(echo "$skill_data" | jq -r '[.[].timestamp] | sort | last')

  # 建议 budget:p50 做预估,p90 做报警阈值
  suggested_budget=$(echo "$stats" | jq '{p50_target: .p50, p90_alert: .p90, note: "样本小,建议累积到 >= 10 次再固化为 rule"}')

  # 产出 pattern MD
  output_file="${patterns_dir}/pattern-token-${skill}-${today}.md"

  cat > "$output_file" <<EOF
---
name: Token 成本模式 · ${skill}
type: cost_pattern
skill: ${skill}
status: pending_review
generated_at: $(date +%Y-%m-%dT%H:%M:%S%z)
samples: $(echo "$stats" | jq -r .samples)
time_range: [${first_ts}, ${last_ts}]
---

# ${skill} · 成本模式(自动聚合)

> 本文件由 \`raw-to-patterns.sh\` 自动产出。**待人工审核**后升级到 \`rules/\`。

## 样本概况

- 样本数:**$(echo "$stats" | jq -r .samples)** 次对话
- 时间范围:${first_ts} → ${last_ts}

## Output Token 分位数(代表 skill 的工作量分布)

\`\`\`json
$(echo "$stats" | jq .)
\`\`\`

## 成本聚合(按 ppio Opus 定价估算,USD)

\`\`\`json
$(echo "$cost" | jq .)
\`\`\`

## 异常点(output > P90 的 run)

\`\`\`json
$(echo "$outliers" | jq .)
\`\`\`

**解读**:异常点通常意味着 skill 流程偶发失控(进入未预期的 phase / 用户多次追加要求)。
应检查这些 session,判断是"合理的高消耗"还是"skill 本身的 bug"。

## 建议 budget(供升级到 rule 时参考)

\`\`\`json
$(echo "$suggested_budget" | jq .)
\`\`\`

## 如何升级为 rule

1. 看样本数够不够($(echo "$stats" | jq -r .samples) < 10 先再观察一轮)
2. 判断 P50/P90 是否稳定(不同周期的 pattern 差异 < 30% 才算稳定)
3. 稳定后,copy 一份到 \`rules/rule-token-${skill}.md\`,加 \`status: approved\`
4. 反哺 SKILL.md:在文件末尾加一行 \`<!-- budget: p50={P50}, p90={P90}, reviewed={日期} -->\`(示意,具体值替换)
5. 这样下一轮 skill 跑完后,可以**自动对照 budget 做异常检测**

---

> Auto-generated by raw-to-patterns.sh · do not edit directly
EOF

  processed=$((processed + 1))
  echo "✅ ${skill}: samples=$(echo "$stats" | jq -r .samples), 写入 $output_file"
done

echo ""
echo "处理完成: ${processed} 个 skill(样本 >= ${min_samples})"
echo "Patterns 目录: ${patterns_dir}"
